import { pool } from '../database/pool.js';
import type { CustomizationCategory, CustomizationOption, CreateCustomizationCategoryInput, UpdateCustomizationCategoryInput, CreateCustomizationOptionInput, UpdateCustomizationOptionInput } from '../types/customization.types.js';

const categoryFields = 'id, name, slug, status, sort_order, created_at, updated_at';
const optionFields = 'id, category_id, name, slug, image_url, image_public_id, description, status, sort_order, created_at, updated_at';
function option(row: Record<string, unknown>): CustomizationOption { return { id: row.id as string, categoryId: row.category_id as string, name: row.name as string, slug: row.slug as string, imageUrl: row.image_url as string | null, imagePublicId: row.image_public_id as string | null, description: row.description as string | null, status: row.status as CustomizationOption['status'], sortOrder: row.sort_order as number, createdAt: (row.created_at as Date).toISOString(), updatedAt: (row.updated_at as Date).toISOString() }; }
function category(row: Record<string, unknown>, options: CustomizationOption[] = []): CustomizationCategory { return { id: row.id as string, name: row.name as string, slug: row.slug as string, status: row.status as CustomizationCategory['status'], sortOrder: row.sort_order as number, createdAt: (row.created_at as Date).toISOString(), updatedAt: (row.updated_at as Date).toISOString(), options }; }
export async function findCustomizationCategories(activeOnly: boolean): Promise<CustomizationCategory[]> {
  const categories = await pool.query(`SELECT ${categoryFields} FROM customization_categories ${activeOnly ? "WHERE status = 'active'" : ''} ORDER BY sort_order, name`);
  if (!categories.rows.length) return [];
  const options = await pool.query(`SELECT ${optionFields} FROM customization_options WHERE category_id = ANY($1::uuid[]) ${activeOnly ? "AND status = 'active'" : ''} ORDER BY sort_order, name`, [categories.rows.map((row) => row.id)]);
  const byCategory = new Map<string, CustomizationOption[]>();
  for (const row of options.rows as Record<string, unknown>[]) { const value = option(row); byCategory.set(value.categoryId, [...(byCategory.get(value.categoryId) ?? []), value]); }
  return (categories.rows as Record<string, unknown>[]).map((row) => category(row, byCategory.get(row.id as string) ?? []));
}
export async function createCategory(input: CreateCustomizationCategoryInput): Promise<CustomizationCategory> { const result = await pool.query(`INSERT INTO customization_categories (name, slug, status, sort_order) VALUES ($1, $2, $3, $4) RETURNING ${categoryFields}`, [input.name, input.slug, input.status ?? 'active', input.sortOrder ?? 0]); return category(result.rows[0] as Record<string, unknown>); }
export async function updateCategory(id: string, input: UpdateCustomizationCategoryInput): Promise<CustomizationCategory | null> { const columns: Record<keyof UpdateCustomizationCategoryInput, string> = { name: 'name', slug: 'slug', status: 'status', sortOrder: 'sort_order' }; const entries = (Object.entries(input) as [keyof UpdateCustomizationCategoryInput, unknown][]).filter(([, value]) => value !== undefined); const result = await pool.query(`UPDATE customization_categories SET ${entries.map(([key], i) => `${columns[key]} = $${i + 1}`).join(', ')} WHERE id = $${entries.length + 1} RETURNING ${categoryFields}`, [...entries.map(([, value]) => value), id]); return result.rows[0] ? category(result.rows[0] as Record<string, unknown>) : null; }
export async function deleteCategory(id: string): Promise<boolean> { return (await pool.query('DELETE FROM customization_categories WHERE id = $1 RETURNING id', [id])).rows.length > 0; }
export async function createOption(input: CreateCustomizationOptionInput): Promise<CustomizationOption | null> { const result = await pool.query(`INSERT INTO customization_options (category_id, name, slug, image_url, image_public_id, description, status, sort_order) SELECT $1, $2, $3, $4, $5, $6, $7, $8 WHERE EXISTS (SELECT 1 FROM customization_categories WHERE id = $1) RETURNING ${optionFields}`, [input.categoryId, input.name, input.slug, input.imageUrl ?? null, input.imagePublicId ?? null, input.description ?? null, input.status ?? 'active', input.sortOrder ?? 0]); return result.rows[0] ? option(result.rows[0] as Record<string, unknown>) : null; }
export async function updateOption(id: string, input: UpdateCustomizationOptionInput): Promise<CustomizationOption | null> { const columns: Record<keyof UpdateCustomizationOptionInput, string> = { categoryId: 'category_id', name: 'name', slug: 'slug', imageUrl: 'image_url', imagePublicId: 'image_public_id', description: 'description', status: 'status', sortOrder: 'sort_order' }; const entries = (Object.entries(input) as [keyof UpdateCustomizationOptionInput, unknown][]).filter(([, value]) => value !== undefined); const result = await pool.query(`UPDATE customization_options SET ${entries.map(([key], i) => `${columns[key]} = $${i + 1}`).join(', ')} WHERE id = $${entries.length + 1} RETURNING ${optionFields}`, [...entries.map(([, value]) => value), id]); return result.rows[0] ? option(result.rows[0] as Record<string, unknown>) : null; }
export async function deleteOption(id: string): Promise<boolean> { return (await pool.query('DELETE FROM customization_options WHERE id = $1 RETURNING id', [id])).rows.length > 0; }
